In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("co2_emission.csv")

In [5]:
df.head(5)

        Entity Code  Year  Annual CO₂ emissions (tonnes )
0  Afghanistan  AFG  1949                         14656.0
1  Afghanistan  AFG  1950                         84272.0
2  Afghanistan  AFG  1951                         91600.0
3  Afghanistan  AFG  1952                         91600.0
4  Afghanistan  AFG  1953                        106256.0

In [5]:
df.shape

(20853, 4)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20853 entries, 0 to 20852
Data columns (total 4 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Entity                          20853 non-null  object
 1   Code                            18646 non-null  object
 2   Year                            20853 non-null  int64
 3   Annual CO₂ emissions (tonnes )  20853 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 651.8+ KB

In [7]:
df["Code"].isnull().sum()

np.int64(2207)

In [8]:
df.describe()

               Year  Annual CO₂ emissions (tonnes )
count  20853.000000                    2.085300e+04
mean    1953.339424                    1.930517e+08
std       57.903089                    1.345143e+09
min     1751.000000                   -6.255223e+08
25%     1932.000000                    3.187680e+05
50%     1971.000000                    3.828880e+06
75%     1995.000000                    3.706898e+07
max     2017.000000                    3.615326e+10

In [13]:
df.dropna(subset=['Code'], inplace=True)

In [14]:
df.shape

(18646, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18646 entries, 0 to 20852
Data columns (total 4 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Entity                          18646 non-null  object
 1   Code                            18646 non-null  object
 2   Year                            18646 non-null  int64
 3   Annual CO₂ emissions (tonnes )  18646 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 728.4+ KB

In [24]:
df.reset_index(drop=True, inplace=True)

In [25]:
df.tail(5)

         Entity Code  Year  Annual CO₂ emissions (tonnes )
18641  Zimbabwe  ZWE  2013                     11536239.29
18642  Zimbabwe  ZWE  2014                     11866348.41
18643  Zimbabwe  ZWE  2015                     10907603.94
18644  Zimbabwe  ZWE  2016                      9932649.88
18645  Zimbabwe  ZWE  2017                     10397718.47

In [37]:
index = df[df['Entity'] == 'World']

In [38]:
df.dropna(inplace=True)

In [40]:
df.reset_index(drop=True, inplace=True)

In [41]:
df.tail()

         Entity Code    Year  Annual CO₂ emissions (tonnes )
18374  Zimbabwe  ZWE  2013.0                     11536239.29
18375  Zimbabwe  ZWE  2014.0                     11866348.41
18376  Zimbabwe  ZWE  2015.0                     10907603.94
18377  Zimbabwe  ZWE  2016.0                      9932649.88
18378  Zimbabwe  ZWE  2017.0                     10397718.47

In [64]:
country_totals = df.groupby('Entity')['Annual CO₂ emissions (tonnes )'].sum()
top_country = country_totals.idxmax()

top_country

'United States'

In [69]:
df['Decade'] = (df['Year'] // 10) * 10

country_totals_Decade = df.groupby('Decade')['Annual CO₂ emissions (tonnes )'].sum()


print("Суммарные выбросы CO₂ по десятилетиям:")
country_totals_Decade.tail(10)

Суммарные выбросы CO₂ по десятилетиям:

Decade
1920.0    3.592168e+10
1930.0    3.548856e+10
1940.0    4.515698e+10
1950.0    6.211509e+10
1960.0    1.092618e+11
1970.0    1.692382e+11
1980.0    1.995629e+11
1990.0    2.282232e+11
2000.0    2.781447e+11
2010.0    2.705707e+11
Name: Annual CO₂ emissions (tonnes ), dtype: float64

In [84]:
uniqe_county = df['Entity'].unique()
uniqe_county

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Anguilla', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bolivia', 'Bonaire Sint Eustatius and Saba',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
       'Cayman Islands', 'Central African Republic', 'Chad', 'Chile',
       'China', 'Christmas Island', 'Colombia', 'Comoros',
       'Republic of the Congo', 'Cook Islands', 'Costa Rica',
       "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao', 'Cyprus',
       'Czech Republic', 'Czechoslovakia',
       'Democratic Republic of Republic of the Congo', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Ethiopia', 'Faeroe Islands', 'Falkland Islands', 'Fiji',
       'Finland', 'France', 'French Guiana', 'French Polynesia', 'Gabon',
       'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece',
       'Greenland', 'Grenada', 'Guadeloupe', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong',
       'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq',
       'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Laos',
       'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macao', 'Macedonia',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius',
       'Mexico', 'Micronesia (country)', 'Moldova', 'Mongolia',
       'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue',
       'North Korea', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Palestine',
       'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines',
       'Poland', 'Portugal', 'Qatar', 'Reunion', 'Romania', 'Russia',
       'Rwanda', 'Saint Helena', 'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal',
       'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Sint Maarten (Dutch part)', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Korea',
       'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname',
       'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tajikistan', 'Tanzania', 'Thailand', 'Timor', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam',
       'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

In [86]:
def get_continent(country):

    # Азия
    asia_countries = ['China', 'India', 'Japan', 'South Korea', 'Indonesia', 
                      'Russia', 'Saudi Arabia', 'Iran', 'Iraq', 'Turkey',
                      'Thailand', 'Vietnam', 'Philippines', 'Malaysia', 'Pakistan',
                      'Bangladesh', 'Afghanistan', 'Uzbekistan', 'Kazakhstan',
                      'North Korea', 'Sri Lanka', 'Myanmar', 'Yemen', 'Nepal',
                      'Taiwan', 'Israel', 'Hong Kong', 'Singapore', 'Jordan',
                      'United Arab Emirates', 'Qatar', 'Kuwait', 'Oman', 'Lebanon',
                      'Georgia', 'Azerbaijan', 'Armenia', 'Bahrain', 'Cyprus',
                      'Bhutan', 'Brunei', 'Cambodia', 'Laos', 'Mongolia',
                      'Tajikistan', 'Turkmenistan', 'Kyrgyzstan', 'Macao', 'Palestine',
                      'Timor', 'Maldives']
    
    # Европа
    europe_countries = ['Germany', 'United Kingdom', 'France', 'Italy', 'Spain',
                        'Poland', 'Netherlands', 'Belgium', 'Sweden', 'Austria',
                        'Switzerland', 'Norway', 'Ireland', 'Denmark', 'Finland',
                        'Portugal', 'Czech Republic', 'Greece', 'Romania', 'Hungary',
                        'Slovakia', 'Croatia', 'Belarus', 'Bulgaria', 'Serbia',
                        'Lithuania', 'Slovenia', 'Latvia', 'Estonia', 'Luxembourg',
                        'Bosnia and Herzegovina', 'Albania', 'North Macedonia',
                        'Moldova', 'Malta', 'Iceland', 'Montenegro', 'Andorra',
                        'Liechtenstein', 'Monaco', 'San Marino', 'Vatican',
                        'Czechoslovakia', 'Soviet Union', 'Yugoslavia']
    
    # Северная Америка
    north_america_countries = ['United States', 'Canada', 'Mexico', 'Guatemala',
                               'Cuba', 'Haiti', 'Dominican Republic', 'Honduras',
                               'Nicaragua', 'El Salvador', 'Costa Rica', 'Panama',
                               'Jamaica', 'Puerto Rico', 'Trinidad and Tobago',
                               'Bahamas', 'Barbados', 'Saint Lucia', 'Grenada',
                               'Belize', 'Antigua and Barbuda', 'Dominica',
                               'Saint Kitts and Nevis', 'Saint Vincent and the Grenadines']
    
    # Южная Америка
    south_america_countries = ['Brazil', 'Argentina', 'Colombia', 'Peru', 'Venezuela',
                               'Chile', 'Ecuador', 'Bolivia', 'Paraguay', 'Uruguay',
                               'Guyana', 'Suriname', 'French Guiana']
    
    # Африка
    africa_countries = ['Nigeria', 'Egypt', 'South Africa', 'Algeria', 'Morocco',
                        'Ethiopia', 'Kenya', 'Tanzania', 'Ghana', 'Democratic Republic of Congo',
                        'Uganda', 'Sudan', 'South Sudan', 'Angola', 'Mozambique',
                        'Madagascar', 'Cameroon', "Cote d'Ivoire", 'Niger', 'Burkina Faso',
                        'Mali', 'Malawi', 'Zambia', 'Senegal', 'Chad', 'Somalia',
                        'Zimbabwe', 'Guinea', 'Rwanda', 'Benin', 'Burundi', 'Tunisia',
                        'South Sudan', 'Togo', 'Sierra Leone', 'Libya', 'Congo',
                        'Central African Republic', 'Liberia', 'Mauritania', 'Eritrea',
                        'Namibia', 'Botswana', 'Gabon', 'Lesotho', 'Guinea-Bissau',
                        'Equatorial Guinea', 'Mauritius', 'Eswatini', 'Djibouti',
                        'Comoros', 'Cabo Verde', 'Sao Tome and Principe', 'Seychelles']
    
    # Океания
    oceania_countries = ['Australia', 'New Zealand', 'Papua New Guinea', 'Fiji',
                         'Solomon Islands', 'Vanuatu', 'New Caledonia', 'French Polynesia',
                         'Samoa', 'Kiribati', 'Micronesia', 'Tonga', 'Marshall Islands',
                         'Palau', 'Tuvalu', 'Nauru', 'Cook Islands', 'Niue']
    
    if country in asia_countries:
        return 'Asia'
    elif country in europe_countries:
        return 'Europe'
    elif country in north_america_countries:
        return 'North America'
    elif country in south_america_countries:
        return 'South America'
    elif country in africa_countries:
        return 'Africa'
    elif country in oceania_countries:
        return 'Oceania'
    else:
        return 'Other'
    

df['Continent'] = df['Entity'].apply(get_continent)

df.head(5)

        Entity Code    Year  Annual CO₂ emissions (tonnes )  Decade Continent
0  Afghanistan  AFG  1949.0                         14656.0  1940.0      Asia
1  Afghanistan  AFG  1950.0                         84272.0  1950.0      Asia
2  Afghanistan  AFG  1951.0                         91600.0  1950.0      Asia
3  Afghanistan  AFG  1952.0                         91600.0  1950.0      Asia
4  Afghanistan  AFG  1953.0                        106256.0  1950.0      Asia

In [87]:
continent_totals = df.groupby('Continent')['Annual CO₂ emissions (tonnes )'].sum()

In [1]:
print(f"Доминирующий континент по выбросам CO₂: {continent_totals.idxmax()}, Выбросы: {continent_totals.max()}")

NameError: name 'continent_totals' is not defined